### ISSUE TITLE
Run against multiple OSes in CI

### ISSUE THREAD

**Issue by Julian** [Julian/Filesystems#37]
See https://travis-ci.org/Julian/Filesystems/builds/474049767 and b96485f9224312f15d8d08a30bd10c8b9be82eba though, since ugh fucking things... Who knows how to get that to correctly multiply, might need to abandon tox-travis.

**Comment by altendky** [comment]
AFAIK Travis doesn't provide the multiplicity of Pythons for OSX (or Windows).  Since they also don't provide _any_ storage (artifacts, caching, etc) you have to provide your own Python for _every_ build (OSX might be brew or brew+pyenv).  Circle doesn't provide Pythons either but they do provide caching.  Here's my latest effort at getting triple-platform testing.

https://github.com/sunu/qt5reactor/pull/24/files

While I would really like to have just one site for all three operating systems (Travis...) it's lack of storage is a pain.  Then again, maybe I just need to give in and setup some (shared?) third party caching of Python installs...  plus short-term artifact storage.

**Comment by Julian** [comment]
If I understand what you mean, I'm actually totally OK if travis doesn't handle installing Python, if it provides brew it's trivial to install yourself.

The issue is that it literally lies and says that having `os: -linux / -osx` will cause all the `matrix.include`s to run across each of those, when instead I got some crazy build that didn't do any of that, it actually just added a *new* "Python" environment (rather than 2.7, 3.6, etc.) and ran only that one environment on both OSes, which broke on both, because that environment didn't have any Python installed.

My *guess* is that that's `tox-travis`'s fault, which I really strongly dislike anyhow, and that it's just passing the wrong things in its yml that it's generating or some other craziness, but it's really just crazy turtles all the way down so who knows if I have the energy to diagnose what's up.

But yeah definitely agreed with your last paragraph :)

**Comment by altendky** [comment]
The cost of not having a python already there is the time spent building it for every environment for every os for every ci build.  Sorry, I don't have actual numbers of what that is.  I'm getting more tempted though to do my own caching, as annoying as that is.  It would be knowledge/service/tooling I could use wherever.

**Comment by altendky** [comment]
The existing `.travis.yml` isn't really using the matrixing feature (`python` is inside matrix/include, not at the top level like you added `os`).  I never did figure out how to modify single matrix elements to add the xenial/sudo so I've mostly just ignored the matrixing feature.  I didn't want to use xenial for everything since it wasn't the official build and didn't want to use sudo since it was slower.

But...  Travis just recently deprecated the trusty container so xenial is now official apparently (though I think I found it wasn't default...) and we're not supposed to sudo:false either I guess.

https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments

https://docs.travis-ci.com/user/reference/xenial/

Anyways, we seem to be able to get 3.4/5/6/7 now via the 'regular' matrix method (or maybe we always good and I just don't care about runtime hits anymore) so we could switch back to that.  Runtimes seem vaguely similar.

https://travis-ci.org/altendky/altendpy/builds/474479295?utm_source=github_status&utm_medium=notification

I'll make a PR for that switch (without adding osx) and we can see how it looks.

**Comment by altendky** [comment]
#39

**Comment by altendky** [comment]
Also #40 (built on top of #39).  Perhaps this is more the job list you were going for?

https://travis-ci.org/Julian/Filesystems/builds/474491482?utm_source=github_status&utm_medium=notification

Aside from the error for any Python version on OSX...

```
2.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/osx/10.13/x86_64/python-2.7.tar.bz2
$ curl -sSf -o python-2.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 2.7 archive. The archive may not exist. Please consider a different version.
```

hoorah, time to search and read.

https://docs.travis-ci.com/user/reference/osx/#python-related-tools
https://docs.travis-ci.com/user/reference/windows/#supported-languages

They support 'Bash variants' on Windows, but not Python.
